### ISSUE TITLE
Thread 'main' panicked at 'gl function was not loaded'

### ISSUE THREAD

**Issue by josepmy** [anopara/country-slice#3]
Hi,
After install Rust on macosx and compile the repo appear this error. 

Any idea about this error? I'm new to Rust.

`INFO [country_slice::setup] Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: Some(4), srgb: true }
thread 'main' panicked at 'gl function was not loaded', /Users/joss/Downloads/country-slice-main/target/release/build/gl-91567117508283f4/out/bindings.rs:20624:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
TRACE [winit::platform_impl::platform::window] Dropping `UnownedWindow` (0x7faba7e357e0)
iMac-de-Joss:country-slice-main joss$ cargo run --release RUST_BACKTRACE=1
warning: unused import: `gl::types::*`
 --> src/geometry/instanced_wall.rs:1:5
  |
1 | use gl::types::*;
  |     ^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `ffi::CString`, `marker::PhantomData`, `os::raw::c_char`, `ptr`
 --> src/geometry/instanced_wall.rs:3:11
  |
3 | use std::{ffi::CString, marker::PhantomData, os::raw::c_char, ptr};
  |           ^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^  ^^^

warning: unused import: `shader::ShaderProgram`
 --> src/geometry/instanced_wall.rs:5:21
  |
5 | use crate::render::{shader::ShaderProgram, ssbo::GLShaderStorageBuffer};
  |                     ^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `DisplayTestMask`
 --> src/systems/startup.rs:9:13
  |
9 | use crate::{DisplayTestMask, IndirectDraw};
  |             ^^^^^^^^^^^^^^^

warning: `country-slice` (bin "country-slice") generated 4 warnings
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/country-slice RUST_BACKTRACE=1`
TRACE [winit::platform_impl::platform::window] Creating new window
TRACE [winit::platform_impl::platform::view] Triggered `viewDidMoveToWindow`
TRACE [winit::platform_impl::platform::view] Completed `viewDidMoveToWindow`
TRACE [winit::platform_impl::platform::view] Triggered `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Completed `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Triggered `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Completed `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Triggered `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::view] Completed `validAttributesForMarkedText`
TRACE [winit::platform_impl::platform::window] Locked shared state in `set_fullscreen`
TRACE [winit::platform_impl::platform::window] Unlocked shared state in `set_fullscreen`
INFO [country_slice::setup] Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: Some(4), srgb: true }
thread 'main' panicked at 'gl function was not loaded', /Users/joss/Downloads/country-slice-main/target/release/build/gl-91567117508283f4/out/bindings.rs:20624:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
TRACE [winit::platform_impl::platform::window] Dropping `UnownedWindow` (0x7ff67cc23850)`

**Comment by anopara** [comment]
Hey @josepmy! Unfortunately, OpenGL is not supported on MacOS, only Windows & Linux

**Comment by josepmy** [comment]
Ops, yes, tomorrow I will try on windows box
