### ISSUE TITLE
Panic on run because glslValidator is not found

### ISSUE THREAD

**Issue by kvark** [anopara/country-slice#5]
>TRACE [mio::poll] registering event source with poller: token=Token(0), interests=READABLE
INFO [winit::platform_impl::platform::x11::window] Guessed window scale factor: 1.5
DEBUG [winit::platform_impl::platform::x11::window] Calculated physical dimensions: 1600x1200
INFO [country_slice::setup] Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: Some(4), srgb: true }
thread 'main' panicked at 'failed to execute process: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/utils/mod.rs:27:14

It's really minor, since you just expect glslvalidator to be present. But maybe the error message could be improved, or the whole thing just skipping validation if it's not found.

Also, you should be able to do it at build time instead of run time.

**Comment by anopara** [comment]
Ah, good point! I should indeed move it out into its a build script 👍 for now, I can sanitize the unwraps

Also, I think on Linux it woudn't work if called with `.exe` extension 🤔 will remove it as well
